sudo: true

language: python
dist: xenial
python: "3.7"

cache: pip

install:
  - pip install tox-travis

script:
  - tox

jobs:
  include:
    - stage: codecov
      python: 3.7
      sudo: true
      dist: xenial
      script:
        - tox
        - pip install codecov && codecov

notifications:
  email: false
